### ISSUE TITLE
Armorstand Editor

### ISSUE THREAD

**Issue by Greazi-Times** [RypoFalem/GhostBuster#1]
Hi there,

I wanted to ask if I could take over your armorstand editor project.
I would like to take the plugin over from you and keep it updated. I like your plugin and I would really love to maintain your project.

--
Kind regards,
Greazi

**Comment by RypoFalem** [comment]
I archived the project for a reason. Opening an issue in a different repo when I purposefully disabled interaction in the original repo is a jerk move.

**Comment by Greazi-Times** [comment]
You can think that it is a jerk move.
But to be fair I also could just copied your code and just updated it without asking. What I think is even worse than me asking.

But that is my opinion.

So than I won't do it no problem  with that
